name: CosmoPlays
version: 1.0
main: pl.gastherr.cosmic.Main
depend: [WorldGuard, Citizens, BukkitSmerf]
commands:
    clearexp:
        description: zabiera exp
    pinfo:
        description: pokazuje informacje o tobie
    setoption:
        description: ustawienia gracza
    dajmenu:
        description: daje menu
    zdejmijkombinezon:
        description: zdejmuje kombinezon
    zalozkombinezon:
        description: zaklada kombinezon
    setexp:
        description: ustawia exp
    upgrade:
        description: upgraduje przedmiot
    setlvl:
        description: ustawia poziom
    clearchat:
        description: czysci czat
    ainfo:
        description: pokazuje informacje o wybranym graczu
    givekombinezon:
        description: daje kombinezon wybranej frakcji
    addfractioninfo:
        description: dodaje informacje nt wybranej frakcji
    fractioninfo:
        description: pokazuje informacje o wybranej frakcji
    money:
        description: pokazuje stan konta
    kasa:
        description: pokazuje stan konta
    sinfo:
        description: pokazuje statystyki serwerowe
    setloc:
        description: ustawia lokalizacje
    delloc:
        description: usuwa lokalizacje
    spawn:
        description: teleportuje na spawn
    setrank:
        description: ustawia range
    delrank:
        description: usuwa range
    mechmenu:
        description: pokazuje menu wyboru mechanizmow
    tptocord:
        description: teleportuje do wybranej lokalizacji
    iteminfo:
        description: info o itemie